const data = {
    products:[
        {
            _id:'1',
            name:'Shirt',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 20,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id:'2',
            name:'Shirt 22222',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 40,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id:'3',
            name:'Shirt',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 20,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id:'4',
            name:'Shirt',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 20,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id:'5',
            name:'Shirt',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 20,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id:'6',
            name:'Shirt',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 20,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id:'7',
            name:'Shirt',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 20,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id:'8',
            name:'Shirt',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 20,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id:'9',
            name:'Shirt',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 20,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id:'10',
            name:'Shirt',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 20,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id:'11',
            name:'Shirt',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 20,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id:'12',
            name:'Shirt',
            category:'Shirts',
            image:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/435806/item/goods_27_435806.jpg?width=2000',
            price: 20,
            brand: 'UNIQLO',
            rating: 5,
            numReviews: 10,
            description: 'High Quality product',
        },
    ],
};

export default data